### ISSUE TITLE
Indexer crashes

### ISSUE THREAD

**Issue by TKlerx** [lociii/jukebox#46]
The indexer crashes if you try to import a lot of songs. Is there anything held in memory or are there any restrictions on the number of songs in the database? Please reply if there is an upper bound on the number so that I do not try to import again ;)

Here is the stack trace:
jukebox jukebox_index --path=/[some path]
Indexing music in /media/truecrypt1
This may take a while
Traceback (most recent call last):
  File "/usr/local/bin/jukebox", line 17, in <module>
    execute_manager(settings)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 459, in execute_manager
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/jukebox/jukebox_core/management/commands/jukebox_index.py", line 25, in handle
    self.index(options["path"], int(options["verbosity"]))
  File "/usr/local/lib/python2.7/dist-packages/jukebox/jukebox_core/management/commands/jukebox_index.py", line 37, in index
    self.index(filename + "/", verbosity)
  File "/usr/local/lib/python2.7/dist-packages/jukebox/jukebox_core/management/commands/jukebox_index.py", line 37, in index
    self.index(filename + "/", verbosity)
  File "/usr/local/lib/python2.7/dist-packages/jukebox/jukebox_core/management/commands/jukebox_index.py", line 37, in index
    self.index(filename + "/", verbosity)
  File "/usr/local/lib/python2.7/dist-packages/jukebox/jukebox_core/management/commands/jukebox_index.py", line 41, in index
    indexer.index(filename)
  File "/usr/local/lib/python2.7/dist-packages/jukebox/jukebox_core/utils.py", line 26, in index
    tags[k] = v[0].lower()

**Comment by TKlerx** [comment]
Sorry for this noob issue. I just caught the IndexError. There was something wrong with only two out of 90.000 files.

**Comment by lociii** [comment]
Can you please provide some more information about what was wrong with those two files. The indexer shouldn't crash, it should skip such files.
